### ISSUE TITLE
Demo seems to be down

### ISSUE THREAD

**Issue by tanvibhakta** [rpearce/react-popover-a11y#24]
Hello! Sorry I can't open a PR to fix this, just wanted to let you know that the demo site for this component seems to be down: [https://rpearce.github.io/react-popover-a11y/](https://rpearce.github.io/react-popover-a11y/) gives me a 404.

Thanks for the work you've put in, looking forward to evaluating it for our usecase!

**Comment by rpearce** [comment]
Thanks for reporting! I fixed this some time ago but forgot to close this out
